# Use an official Python runtime as the parent image
FROM python:3.8
# Set the working directory in the container to /app
WORKDIR /app
# Copy the current directory contents into the container at /app
COPY . /app
#we upgrade pip
RUN pip install --upgrade pip
# Install any needed packages specified in requirements.txt
#RUN pip install --trusted-host pypi.python.org -r requirements.txt
RUN pip install -r requirements.txt
# Make port 5006 available to the world outside this container
EXPOSE 5005
# Define environment variable for Flask to run in production mode
ENV FLASK_ENV=production
# Run ann_api.py when the container launches
CMD ["python", "annoy_bow.py"]
